export const categories = {
  "Restaurant & Hospitality": [
    "Chef", 
    "Sous Chef",
    "Line Cook",
    "Pastry Chef",
    "Server",
    "Bartender",
    "Barback",
    "Host/Hostess",
    "Restaurant Manager",
    "Kitchen Manager",
    "Food Service",
    "Catering",
    "Hospitality Management",
    "Restaurant",
    "Hospitality",
    "Food & Beverage",
    "Culinary",
    "Kitchen Staff",
    "Front of House",
    "Back of House"
  ],
  "Food Industry": [
    "Food Production",
    "Food Safety",
    "Quality Control",
    "Recipe Development",
    "Food Science",
    "Product Development",
    "Kitchen Operations",
    "Food Manufacturing",
    "Food Technology",
    "Food Innovation",
    "Food Distribution",
    "Supply Chain",
    "Procurement",
    "Food Industry",
    "Plant-Based",
    "Alternative Protein",
    "Food Processing",
    "Food Packaging",
    "Quality Assurance",
    "R&D",
    "Research and Development",
    "Food Startups",
    "CPG",
    "Consumer Packaged Goods"
  ],
  "Business & Operations": [
    "Operations Manager",
    "Project Manager",
    "Business Development",
    "Marketing Manager",
    "HR Manager",
    "Finance Manager",
    "Account Manager",
    "Operations",
    "Strategy",
    "Business Strategy",
    "Business Operations",
    "Administration",
    "Executive",
    "Consulting",
    "Business",
    "Management",
    "Finance",
    "Human Resources",
    "HR",
    "Accounting",
    "Legal",
    "Compliance",
    "Risk Management",
    "Operations Management",
    "Supply Chain Management",
    "Logistics",
    "Procurement Management",
    "Business Intelligence",
    "Analytics"
  ],
  "Technology": [
    "Software Engineer",
    "Web Developer",
    "UX Designer",
    "Product Manager",
    "Data Analyst",
    "IT Support",
    "Software Development",
    "Engineering",
    "Technical",
    "Technology",
    "Development",
    "Frontend",
    "Backend",
    "Full Stack",
    "DevOps",
    "Cloud",
    "AWS",
    "Azure",
    "Machine Learning",
    "AI",
    "Artificial Intelligence",
    "Data Science",
    "UI Design",
    "Product Design",
    "Mobile Development",
    "QA",
    "Quality Assurance",
    "Testing",
    "Information Security",
    "Cybersecurity",
    "Network",
    "Systems",
    "Infrastructure"
  ],
  "Retail & Service": [
    "Retail Manager",
    "Sales Associate",
    "Store Manager",
    "Cashier",
    "Customer Service",
    "Visual Merchandiser",
    "Retail",
    "Sales",
    "Service",
    "Merchandising",
    "Inventory Management",
    "Loss Prevention",
    "E-commerce",
    "Online Retail",
    "Retail Operations",
    "Customer Experience",
    "Customer Success",
    "Account Management",
    "Client Services",
    "Business Services"
  ],
  "Marketing & Communications": [
    "Marketing",
    "Communications",
    "Social Media",
    "Digital Marketing",
    "Content Creation",
    "Public Relations",
    "Brand Management",
    "Community Management",
    "Advertising",
    "Content Marketing",
    "Email Marketing",
    "SEO",
    "SEM",
    "Growth Marketing",
    "Marketing Strategy",
    "Brand Strategy",
    "Content Strategy",
    "Copywriting",
    "Creative",
    "Graphic Design",
    "Media Relations",
    "Internal Communications",
    "Corporate Communications",
    "Marketing Analytics",
    "Marketing Operations",
    "Events",
    "Event Marketing",
    "Influencer Marketing",
    "Social Media Marketing",
    "Performance Marketing"
  ],
  "Non-Profit & Advocacy": [
    "Non-Profit",
    "Advocacy",
    "Community Outreach",
    "Program Management",
    "Volunteer Management",
    "Fundraising",
    "Grant Writing",
    "Animal Rights",
    "Animal Welfare",
    "Vegan Advocacy",
    "Social Impact",
    "Environmental",
    "Sustainability",
    "Conservation",
    "Policy",
    "Activism",
    "Campaign Management",
    "Donor Relations",
    "Development",
    "Non-Profit Management",
    "Social Justice",
    "Community Engagement",
    "Grassroots",
    "Animal Protection",
    "Animal Care",
    "Wildlife",
    "Environmental Justice",
    "Climate",
    "Social Services",
    "Philanthropy"
  ],
  "Education & Research": [
    "Education",
    "Research",
    "Teaching",
    "Training",
    "Curriculum Development",
    "Program Development",
    "Academic",
    "Instructional Design",
    "E-learning",
    "Educational Technology",
    "Higher Education",
    "Adult Education",
    "Professional Development",
    "Learning & Development",
    "Research Analysis",
    "Research Coordination",
    "Scientific Research",
    "Market Research",
    "Data Analysis",
    "Policy Research",
    "Research Management"
  ],
  "Employment Type": [
    "Full-time",
    "Part-time",
    "Contract",
    "Internship",
    "Remote",
    "Hybrid",
    "Temporary",
    "Freelance",
    "Volunteer",
    "Permanent",
    "Fixed-term",
    "Seasonal",
    "On-site",
    "Flexible"
  ],
  "Experience Level": [
    "Entry Level",
    "Mid Level",
    "Senior",
    "Lead",
    "Manager",
    "Director",
    "Executive",
    "Junior",
    "Associate",
    "Principal",
    "C-Level",
    "VP",
    "Head",
    "Chief",
    "Specialist",
    "Expert",
    "Professional",
    "Coordinator",
    "Supervisor",
    "Administrator"
  ],
  "Other Skills": [
    "Writing",
    "Editing",
    "Analysis",
    "Leadership",
    "Project Management",
    "Event Planning",
    "Customer Relations",
    "Coordination",
    "Design",
    "Planning",
    "Management",
    "Problem Solving",
    "Communication",
    "Presentation",
    "Negotiation",
    "Budgeting",
    "Strategic Planning",
    "Team Management",
    "Time Management",
    "Change Management",
    "Process Improvement",
    "Innovation",
    "Collaboration",
    "Critical Thinking",
    "Decision Making",
    "Mentoring",
    "Coaching",
    "Stakeholder Management",
    "Risk Assessment",
    "Quality Management"
  ]
};