export const businessCategories = [
  "Operations Manager",
  "Project Manager",
  "Business Development",
  "Marketing Manager",
  "HR Manager",
  "Finance Manager",
  "Account Manager",
  "Operations",
  "Strategy",
  "Business Strategy",
  "Business Operations",
  "Administration",
  "Executive",
  "Consulting",
  "Business",
  "Management",
  "Finance",
  "Human Resources",
  "HR",
  "Accounting",
  "Legal",
  "Compliance",
  "Risk Management",
  "Operations Management",
  "Supply Chain Management",
  "Logistics",
  "Procurement Management",
  "Business Intelligence",
  "Analytics"
];