export const foodIndustryCategories = [
  "Food Production",
  "Food Safety",
  "Quality Control",
  "Recipe Development",
  "Food Science",
  "Product Development",
  "Kitchen Operations",
  "Food Manufacturing",
  "Food Technology",
  "Food Innovation",
  "Food Distribution",
  "Supply Chain",
  "Procurement",
  "Food Industry",
  "Plant-Based",
  "Alternative Protein",
  "Food Processing",
  "Food Packaging",
  "Quality Assurance",
  "R&D",
  "Research and Development",
  "Food Startups",
  "CPG",
  "Consumer Packaged Goods"
];