export const healthcareCategories = [
  "Healthcare",
  "Health",
  "Medical",
  "Wellness",
  "Nutrition",
  "Mental Health",
  "Public Health",
  "Health Education",
  "Health Policy",
  "Health Technology",
  "Healthcare Management",
  "Clinical",
  "Pharmaceutical",
  "Biotech",
  "Health Research",
  "Health Innovation",
  "Health Services",
  "Preventive Care",
  "Alternative Medicine",
  "Holistic Health"
];