export const legalCategories = [
  "Legal",
  "Law",
  "Compliance",
  "Regulatory",
  "Policy",
  "Advocacy",
  "Legal Affairs",
  "Corporate Law",
  "Environmental Law",
  "Food Law",
  "Animal Law",
  "Public Policy",
  "Government Relations",
  "Legal Counsel",
  "Legal Services",
  "Legal Research",
  "Legal Writing",
  "Contracts",
  "Intellectual Property",
  "Regulations"
];