export const marketingCategories = [
  "Marketing",
  "Communications",
  "Social Media",
  "Digital Marketing",
  "Content Creation",
  "Public Relations",
  "Brand Management",
  "Community Management",
  "Advertising",
  "Content Marketing",
  "Email Marketing",
  "SEO",
  "SEM",
  "Growth Marketing",
  "Marketing Strategy",
  "Brand Strategy",
  "Content Strategy",
  "Copywriting",
  "Creative",
  "Graphic Design",
  "Media Relations",
  "Internal Communications",
  "Corporate Communications",
  "Marketing Analytics",
  "Marketing Operations",
  "Events",
  "Event Marketing",
  "Influencer Marketing",
  "Social Media Marketing",
  "Performance Marketing"
];