export const nonProfitCategories = [
  "Non-Profit",
  "Advocacy",
  "Community Outreach",
  "Program Management",
  "Volunteer Management",
  "Fundraising",
  "Grant Writing",
  "Animal Rights",
  "Animal Welfare",
  "Vegan Advocacy",
  "Social Impact",
  "Environmental",
  "Sustainability",
  "Conservation",
  "Policy",
  "Activism",
  "Campaign Management",
  "Donor Relations",
  "Development",
  "Non-Profit Management",
  "Social Justice",
  "Community Engagement",
  "Grassroots",
  "Animal Protection",
  "Animal Care",
  "Wildlife",
  "Environmental Justice",
  "Climate",
  "Social Services",
  "Philanthropy",
  "NGO",
  "Charitable",
  "Social Work",
  "Community Development",
  "Impact Assessment",
  "Program Coordination",
  "Outreach",
  "Education Outreach",
  "Animal Sanctuary",
  "Animal Shelter",
  "Rescue",
  "Plant-Based Advocacy",
  "Environmental Education",
  "Conservation Biology"
];