export const nonProfitCategories = [
  "Non-Profit",
  "Advocacy",
  "Community Outreach",
  "Program Management",
  "Volunteer Management",
  "Fundraising",
  "Grant Writing",
  "Animal Rights",
  "Animal Welfare",
  "Vegan Advocacy",
  "Social Impact",
  "Environmental",
  "Sustainability",
  "Conservation",
  "Policy",
  "Activism",
  "Campaign Management",
  "Donor Relations",
  "Development",
  "Non-Profit Management",
  "Social Justice",
  "Community Engagement",
  "Grassroots",
  "Animal Protection",
  "Animal Care",
  "Wildlife",
  "Environmental Justice",
  "Climate",
  "Social Services",
  "Philanthropy"
];