export const skillsCategories = [
  "Writing",
  "Editing",
  "Analysis",
  "Leadership",
  "Project Management",
  "Event Planning",
  "Customer Relations",
  "Coordination",
  "Design",
  "Planning",
  "Management",
  "Problem Solving",
  "Communication",
  "Presentation",
  "Negotiation",
  "Budgeting",
  "Strategic Planning",
  "Team Management",
  "Time Management",
  "Change Management",
  "Process Improvement",
  "Innovation",
  "Collaboration",
  "Critical Thinking",
  "Decision Making",
  "Mentoring",
  "Coaching",
  "Stakeholder Management",
  "Risk Assessment",
  "Quality Management"
];