export const technologyCategories = [
  "Software Engineer",
  "Web Developer",
  "UX Designer",
  "Product Manager",
  "Data Analyst",
  "IT Support",
  "Software Development",
  "Engineering",
  "Technical",
  "Technology",
  "Development",
  "Frontend",
  "Backend",
  "Full Stack",
  "DevOps",
  "Cloud",
  "AWS",
  "Azure",
  "Machine Learning",
  "AI",
  "Artificial Intelligence",
  "Data Science",
  "UI Design",
  "Product Design",
  "Mobile Development",
  "QA",
  "Quality Assurance",
  "Testing",
  "Information Security",
  "Cybersecurity",
  "Network",
  "Systems",
  "Infrastructure",
  "Database",
  "Software Architecture",
  "Technical Lead",
  "System Administration",
  "Technical Support",
  "IT Operations",
  "Programming",
  "Web Development",
  "Mobile",
  "iOS",
  "Android",
  "React",
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "Ruby",
  "PHP"
];